org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=aitk
mod.name=Arrow In The Knee
mod.group=com.github.razorplay01
mod.version=1.0.3
mod.channel_tag=
mod.authors=RazorPlay01
mod.contributors=
mod.license=MIT
mod.description=Mod that allows arrows to be rendered on all types of entities, not just players
mod.sources_url=https://github.com/RazorPlay01/AITK
mod.homepage_url=https://github.com/RazorPlay01
mod.issues_url=https://github.com/RazorPlay01/AITK/issues
mod.discord_url=https://discord.gg/YP3wDfqkRt

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]

publish.modrinth=A0W9tMly
publish.curseforge=1499353
publish.github=true
